### ISSUE TITLE
print 2-1

### ISSUE THREAD

**Issue by alewissandy** [alewissandy/Flexihand2#5]

**Comment by dlewissandy** [comment]
started

**Comment by dlewissandy** [comment]
This print fails.   A piece of it isn't on the raft and it falls off after about 30% of the build is complete.

**Comment by dlewissandy** [comment]
This piece cannot be printed. Part of it is not on the raft. Arron, can you try laying it out again. Rotating it 45 degrees on the z axis might solve the problem

**Comment by dlewissandy** [comment]
Great idea to print it upside down.  Done.
